title: INFINTY 23
description: > # this means to ignore newlines until "baseurl:"
  INFINITY is the first annual event of Kathmandu University Computational Mathematics Club
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2016_style/img/icon-large.png"

social:
  name: Kathmandu University Computational Mathematics Club
  link: "https://www.facebook.com/kucmc1"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages','_2023_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kucmc1
  - title: instagram
    url: https://www.instagram.com/kucmc.official/
  - title: tiktok
    url: https://www.tiktok.com/@math_ku

# Build settings
markdown: kramdown
permalink: pretty
